### ISSUE TITLE
Issue Setting Up Processing Server

### ISSUE THREAD

**Issue by MatthewSabia** [smartscenes/multiscan#13]
I have been trying to set up the processing server on my desktop by following the instructions at https://3dlg-hcvc.github.io/multiscan/read-the-docs/server/index.html#installation.

I have run into some issues, but have gotten to the cmake Build and Install step. When trying to execute cmake in the build directory, there is an error stating CMakeLists.txt is not found. I tried copying the CMakeLists.txt from the parent multiscan folder into build folder, but when running cmake I get

No download info given for 'segmentator' and its source directory:

   ~/multiscan/build/segmentator

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  ~/anaconda3/envs/multiscan/share/cmake-3.24/Modules/ExternalProject.cmake:4170 (_ep_add_download_command)
  CMakeLists.txt:128 (ExternalProject_Add)

**Comment by SamMaoYS** [comment]
Thank you @MatthewSabia for reporting the issues.

We found the issue is caused by the wrong [PREFIX](https://github.com/smartscenes/multiscan/commit/d2728673127e257e2c6bd43ab4d23658b4e056aa#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR130) defined in the CMakeLists.txt for the segmentator. The prefix was set to `CMAKE_CURRENT_SOURCE_DIR`, but it is not correct, it should be the `BUILD_DIR`.

The issue should be fixed in the new commit. Can you try out the new commit, and let us know if the issue is fixed? 

Thank you!

**Comment by MatthewSabia** [comment]
I removed the cloned repository from my computer then re cloned it, copied the CMakeLists.txt file into the build folder and tried again, but I am still getting the same issue once I run the same cmake command. Am I missing a step somewhere?

**Comment by SamMaoYS** [comment]
Hi @MatthewSabia , I think you don't need to copy the CMakeLists.txt into the build folder, the CMakeLists.txt will be cloned and be in the root directory of the repo.

For the testing purpose, you can build the segmentator only, by setting `MTS_BUILD_INSTANTMESHES`, `MTS_BUILD_OPEN3D`, `MTS_BUILD_MVS_TEXTURING` to `OFF`.
